1 - Array: Un array es una estructura de datos que permite almacenar y manipular una 
colección de elementos de un mismo tipo de dato. En Python, los arrays son. 
Para usar un array debemos usar un modulo o debes importar la libreria numpy

In [2]:
import array as vector
my_array = vector.array('i', [1,2,3,4,5,6,7,8,9,10])
print(type(my_array))

<class 'array.array'>


In [5]:
import numpy as np
my_array = np.array([1,2,3,4,5,6,7,8,9,10])
print(type(my_array))


<class 'numpy.ndarray'>


2 - Los Arrays no pueden contener tipos de datos diferentes


In [3]:
import array
my_array = array.array('i'['string',1,2,3,4,5,6,7,8,9,10, 11.8, True])
print(type(my_array[0]))

<>:2: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:2: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\vikto\AppData\Local\Temp\ipykernel_5584\700330941.py:2: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
  my_array = array.array('i'['string',1,2,3,4,5,6,7,8,9,10, 11.8, True])
C:\Users\vikto\AppData\Local\Temp\ipykernel_5584\700330941.py:2: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
  my_array = array.array('i'['string',1,2,3,4,5,6,7,8,9,10, 11.8, True])
C:\Users\vikto\AppData\Local\Temp\ipykernel_5584\700330941.py:2: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
  my_array = array.array('i'['string',1,2,3,4,5,6,7,8,9,10, 11.8, True])


TypeError: string indices must be integers

In [7]:
import numpy
my_array = numpy.array(['string', 3, 7.8, True])
print(my_array)
print(type(my_array[2]))


['string' '3' '7.8' 'True']
<class 'numpy.str_'>


3 - Debe contener elementos del mismo tamaño

// - Los Arrays deben contener el mismo tamaño en cada uno de sus elementos. Ambos vectores deben tener la misma longitud.

In [8]:
import numpy
my_array = numpy.array["Manzana", "Pera", "Cereza"],
["String"],
["Bmw", "Mercedes"]
print(my_array)
print(type(my_array))


TypeError: 'builtin_function_or_method' object is not subscriptable

4 - Anidamiento de Listas


// - Para anidar listas hay que recordar que debes aperturar con doble corchetes "[[" y cerrar al final "]]" de la misma forma. Recordando que cada nombre de la lista debe: 
1- Ir entre comillas dobles " ". 
2- Separar cada elemento con una coma ",". 
3- Para anidar, cada elemento o nombre de elemento debe ir entre corchetes "[]" y finalizado con una coma "," antes del salto de linea, hasta que se complete la lista cerrando el anidamiento con doble corchetes "]]".

In [ ]:
lista_de_listas = [["Manzana", "Pera", "Cereza", "String", "Bmw", "Mercedes"]]
print(type(lista_de_listas))



<class 'list'>


In [10]:
lista_de_listas = [["Manzana", "Pera", "Cereza"], 
["String"], 
["Bmw", "Mercedes"]]
print(type(lista_de_listas))

<class 'list'>


5 - Podemos crear Arrays con numpy.arange(): Tema 4 Arrays, Clase 1

In [1]:
import numpy as np
my_array = np.arange(1,8)
print(my_array)
print(type(my_array))

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


6 - Creando Arrays

// Ejemplo 1: Crea un array usando (np.zeros) para llenarlo con 0, el cual tendra 3 filas y 3 columnas con tipo numeros enteros de 64 Bit. Luego debemos cambiar el valor de las filas y la columna renombrando el Array, indicando que cada elemento de la matriz o Array sea igual a 2. Finalmente imprimir el Array.  

In [8]:
import numpy as np

a = np.zeros((3,3), dtype= np.int64)
a [:] = 2
print (a)


[[2 2 2]
 [2 2 2]
 [2 2 2]]


// Ejemplo 2: Creamos un Array importando la libreria numpy, usando la funcion (.arange) luego indicamos la longitud del array comenzando en; (1, y terminando en 10), el Array debemos modificarlo y cambiarlo de forma. La nueva forma debe tener 3 filas y 3 columnas. Esto lo hacemos utilizando la funcion (.reshape) Finalmente mostramos el Array con la funcion print.

In [7]:
b= np.arange(1,10)
print (b)
b = b.reshape((3,3))
print (b)


[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


8 - Llenar Arrays de valores

// - Ejemplo 1: Creando un Array (a) con el metodo de la funcion (.fill), indicamos el tipo de Array (entero), ademas la cantidad de bits (64) y el valor inicial o contenido de dicho Array (a[:] = 2). Luego de haber creado el array debemos cmabiar los valores iniciales y rellenarlos con el metodo (.fill). El nuevo valor seria (8), (a.fill(8)). Finalmente imprimimos el Array (a).

In [1]:
import numpy as np

a = np.zeros((3,3), dtype= np.int64)
a [:] = 2
a.fill (8)
print (a)


[[8 8 8]
 [8 8 8]
 [8 8 8]]


// - Ejemplo 2: Con operadores de asiganción ( + ). Creando un Array (a) con el metodo de la funcion (.zeros), indicamos el tipo de Array (entero), ademas la cantidad de bits (64) y el valor inicial o contenido de dicho Array (a[:] = 2). Luego de haber creado el array debemos cambiar los valores iniciales y rellenarlos con el operador de asignacion a (+= 6). El nuevo valor del Array (a) seria la suma de la asignacion inicial mas el nuevo valor que le indiquemos se agregue al existente. Finalmente imprimimos el Array (a).

In [ ]:
import numpy as np

a = np.zeros((3,3), dtype= np.int64)
a [:] = 2
a += 6
print (a)


// - Eejmplo 3: Con operadores de asiganción ( - ). Creando un Array (a) con el metodo de la funcion (.zeros), indicamos el tipo de Array (entero), ademas la cantidad de bits (64) y el valor inicial o contenido de dicho Array (a[:] = 2). Luego de haber creado el array debemos cambiar los valores iniciales y rellenarlos con el operador de asignacion a (-= 6). El nuevo valor del Array (a) seria la suma de la asignacion inicial mas el nuevo valor que le indiquemos se agregue al existente. Finalmente imprimimos el Array (a).

In [ ]:
import numpy as np

a = np.zeros((3,3), dtype= np.int64)
a [:] = 2
a -= 6
print (a)


// Ejemplo 4: Con operadores de asiganción ( * ). Creando un Array (a) con el metodo de la funcion (.zeros), indicamos el tipo de Array (entero), ademas la cantidad de bits (64) y el valor inicial o contenido de dicho Array (a[:] = 2). Luego de haber creado el array debemos cambiar los valores iniciales y rellenarlos con el operador de asignacion a (*= 6). El nuevo valor del Array (a) seria la suma de la asignacion inicial mas el nuevo valor que le indiquemos se agregue al existente. Finalmente imprimimos el Array (a).

In [ ]:
import numpy as np

a = np.zeros((3,3), dtype= np.int64)
a [:] = 2
a *= 6
print (a)


// - Eejmplo 5: Con operadores de asiganción ( / ). Creando un Array (a) con el metodo de la funcion (.zeros), indicamos el tipo de Array de division (/) en el mismo no podemos declarar el Array con (dtype) porque daria un error conocido, el array debe mantenerse sin asignacion de datos especifico o declarado. Ademas y por tanto, no hace falta declara la cantidad de bits (64). El valor inicial o contenido de dicho Array sera (a[:] = 2). Luego de haber creado el array debemos cambiar los valores iniciales y rellenarlos con el operador de asignacion a (/= 6). El nuevo valor del Array (a) seria la division de la asignacion inicial entre el nuevo valor que le indiquemos se agregue al existente. Finalmente imprimimos el Array (a).

In [3]:
import numpy as np

a = np.zeros((3,3))
a [:] = 2
a /= 6
print (a)


[[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]


8 - Sumar Arrays

// Ejemplo 1, Suma de todos los elementos del Array: Creamos un Array para sumar los elementos de los Arrays con (.sum()). Indicamos el rango del array de (1,10). Luego le indicamos la forma de Array o matriz, filas y columnas, (3,3). Seguidamente impre el Array en una linea y en otra linea imprime la suma del contenido de los elemntos del Array.


In [2]:
import numpy as np

b = np.arange(1, 10).reshape((3, 3))
suma_array = b.sum()
print (b)
print(suma_array)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
45


// Ejemplo 2, Suma de las columnas del Array: Creando un array con suma cero sum(0). Que sume las columnas del Vector

In [8]:
import numpy as np

b = np.arange(1, 10).reshape((3, 3))
suma_array = b.sum(axis = 0)
print (b, "Array o Matriz del 1 al 9. Inicia la posicion desde 0.")
print("\n")
print(suma_array, "Suma de las columnas del Array")

[[1 2 3]
 [4 5 6]
 [7 8 9]] Array o Matriz del 1 al 9. Inicia la posicion desde 0.


[12 15 18] Suma de las columnas del Array


// Ejemplo 3, Suma de las Filas del Array: Creando un Array que sume las filas del Vector. 

In [7]:
import numpy as np

b = np.arange(1, 10).reshape((3,3))
suma_array = b.sum(axis=1)
print(b)
print("\n")
print(suma_array)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


[ 6 15 24]


9- Multiplicar Arrays

// Ejemplo 1: Crear un Array y utilizar la funcion (.prod) para multiplicar todos los elementos del Array. Y asi mismo dar una forma al vector o generar una matriz de (3x3)

In [ ]:
import numpy as np

b = np.arange(1,10).reshape((3,3))
prod_array = b.prod()
print(b)
print("\n")
print(prod_array, "Resultado de la multiplicación de todos los elementos del array") 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


362880


// Ejemplo 2: Crear un Array que multiplique las columnas del Vector o Matriz.

In [20]:
import numpy as np

b = np.arange(1,10).reshape((3,3))
prod_array = b.prod(axis=0)
print(b)
print("\n")
print(prod_array, " ¡ Resultado de la multiplicación de las columnas del array ! ") 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[ 28  80 162]  ¡ Resultado de la multiplicación de las columnas del array ! 


// Ejemplo 3: Crear un Array que multiplique las filas del vector o Array. Y genere una matriz de 3x3.

In [15]:
import numpy as np

b = np.arange(1,10).reshape((3,3))
prod_array = b.prod(axis=1)
print(b)
print("\n")
print(prod_array, " ¡ Resultado de la multiplicación de las filas del array ! ") 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[  6 120 504]  ¡ Resultado de la multiplicación de las filas del array ! 


10 - Maximo - Minimo y Valor Medio de los Elementos de un Array

// Ejemplo 1: Crear una Array donde hayes el Valor Medio de todos los elementos del Vector o Matriz

In [23]:
import numpy as np

b = np.arange(1,10).reshape((3,3))
mean_array = b.mean()
print(b)
print("\n")
print(mean_array, " ¡ Resultado de encontrar el valor medio de todos los elementos del array ! ")

[[1 2 3]
 [4 5 6]
 [7 8 9]]


5.0  ¡ Resultado de encontrar el valor medio de todos los elementos del array ! 


// Ejemplo 2: Crear un Array que permita encontrar el valor Maximo de todos los elementos del Array.


In [24]:
import numpy as np

b = np.arange(1,10).reshape((3,3))
max_array = b.max()
print(b)
print("\n")
print(max_array, " ¡ Resultado de encontrar el valor medio de todos los elementos del array ! ")

[[1 2 3]
 [4 5 6]
 [7 8 9]]


9  ¡ Resultado de encontrar el valor medio de todos los elementos del array ! 


// Ejemplo 3: Crear un Array que encuentre el Minimo valor del vector.

In [28]:
import numpy as np

b = np.arange(1,10).reshape((3,3))
min_array = b.min()
print(b)
print("\n")
print(f"El numero {min_array}, Es el resultado de encontrar el valor minimo de todos los elementos del array ! ")

[[1 2 3]
 [4 5 6]
 [7 8 9]]


El numero 1, Es el resultado de encontrar el valor minimo de todos los elementos del array ! 


11 - Indices de Arrays y Obtencion Maximos y Minimos de los elementos de Arrays

// Ejemplo 1: Crear un Array y encontrar el Minimo del Indice de todos los elementos del Array

In [5]:
import numpy as np

b = np.arange(1,10).reshape((3,3))
min_array_id= b.argmin()
print(b)
print("\n")
print(f"El numero {min_array_id}, Es el resultado de encontrar el valor del (Idice Minimo) de todos los elementos del array ! ")

[[1 2 3]
 [4 5 6]
 [7 8 9]]


El numero 0, Es el resultado de encontrar el valor del (Idice Minimo) de todos los elementos del array ! 


// Ejemplo 2: Crear un Array y encontrar el valor maximo del Indice de todos los elementos del Array
// https://www.w3schools.com/python/python_arrays.asp

In [4]:
import numpy as np

b = np.arange(1,10).reshape((3,3))
min_array_id= b.argmax()
print(b)
print("\n")
print(f"El numero {min_array_id}, Es el resultado de encontrar el valor del (Indice Maximo) de todos los elementos del array ! ")

[[1 2 3]
 [4 5 6]
 [7 8 9]]


El numero 8, Es el resultado de encontrar el valor del (Indice Maximo) de todos los elementos del array ! 


12 - Aplanar un Array usando: .reshape() + size

// Ejemplo 1: Aplanar un Array; 

In [8]:
import numpy as np

b = np.arange(1,10).reshape((3,3))
array_plano = b.reshape(b.size)
print(b)
print("\n")
print(f"La matriz anterior se ha convertido en un array plano: {array_plano}, Este es el resultado en dar formato o aplanar todos los elementos del array ! ")

[[1 2 3]
 [4 5 6]
 [7 8 9]]


La matriz anterior se ha convertido en un array plano: [1 2 3 4 5 6 7 8 9], Este es el resultado en dar formato o aplanar todos los elementos del array ! 


// Ejemplo 2: Aplanar Array usando: .flatten() "Este metodo crea una copia alternativa del Array" Puede modificarse sin afectar el original. Crea un Clon independiente del Array original.

In [ ]:
import numpy as np

b = np.arange(1,10).reshape((3,3))
array_plano= b.flatten()
print(b)
print("\n")
print(f"El numero {array_plano}, Es el resultado de aplanar y clonar todos los elementos del array con Flatten() ! ")

[[1 2 3]
 [4 5 6]
 [7 8 9]]


El numero [1 2 3 4 5 6 7 8 9], Es el resultado de aplanar el con Flatten() ! 


// Ejemplo 3: Pasar de Lineas a Columnas usando .ravel(). "Crea una copia del Array en la cual, se modificaria el original en caso de realizar cualquier cambio en la copia". Afectando ambos Arrays. Crea un Espejo del mismo.

In [11]:
import numpy as np

b = np.arange(1,10).reshape((3,3))
array_plano= b.ravel()
print(b)
print("\n")
print(f"El numero {array_plano}, Es el resultado de crear un espejo de todos los elementos del array con .ravel() ! ")

[[1 2 3]
 [4 5 6]
 [7 8 9]]


El numero [1 2 3 4 5 6 7 8 9], Es el resultado de crear un espejo de todos los elementos del array con .ravel() ! 


13 - Arrays, Pasar de Lineas y Columnas a tener todo en una Linea

// Ejemplo de 1: Pasar de Filas a Columnas los valores de un Array.

In [16]:
import numpy as np

b = np.arange(1,10).reshape((3,3))
array_transp = np.swapaxes(b, 0, 1)
print(b)
print("\n")
print(f"Este es el resultado de Transponer los elementos de Filas a Columnas del array con .swapaxes() ! ")
print(" ")
print(array_transp)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


Este es el resultado de Transponer los elementos de Filas a Columnas del array con .swapaxes() ! 
 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


// Ejemplo 2: Pasar de Filas a Columnas los datos de la matriz o Valores de un array.

In [18]:
import numpy as np

b = np.arange(1,10).reshape((3,3))
array_transp = b.transpose(1, 0)
print(b)
print("\n")
print(f"Este es el resultado de Transponer los elementos de Filas a Columnas del array con .stranspose() ! ")
print(" ")
print(array_transp)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Este es el resultado de Transponer los elementos de Filas a Columnas del array con .stranspose() ! 
 
[[1 4 7]
 [2 5 8]
 [3 6 9]]
